rules:
  class-name-format:
    - 1
    - convention: hyphenatedbem
  clean-import-paths:
    - 0
    - filename-extension: false
      leading-underscore: false
  empty-line-between-blocks:
    - 0
    - ignore-single-line-rulesets: true
  force-element-nesting: 0
  mixins-before-declarations: 0
  no-color-literals: 0
  no-important: 0
  no-mergeable-selectors: 0
  no-vendor-prefixes:
    - 0
    - additional-identifiers: []
      excluded-identifiers: []
  no-url-domains:
    - 0
  no-url-protocols:
    - 0
  nesting-depth:
    - 2
    - max-depth: 4
